##### General #################################################
set -g prefix C-t
bind C-t send-prefix
unbind C-b

set -g base-index 1
set -g pane-base-index 1
set -g renumber-window on

set -g allow-rename off
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
set -g default-terminal 'tmux-256color'
set -ag terminal-overrides ',xterm-256color*:RGB'

## Basic Option
set -g xterm-keys on
set -g repeat-time 0
set -g focus-events on
set -sg escape-time 10
set -g history-limit 50000
set -g mode-keys vi
set -g set-clipboard on

##### Keybindings #############################################
bind s split-window -v
bind v split-window -h

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 5

bind -r e kill-pane -a

##### Catppuccin v2 Custom Modules #############################

# # --- 1. ctp_cpu ---
# set -gq '@cpu_low_bg_color' '#{E:@thm_green}'
# set -gq '@cpu_medium_bg_color' '#{E:@thm_yellow}'
# set -gq '@cpu_high_bg_color' '#{E:@thm_red}'
#
# set -gq "@catppuccin_ctp_cpu_icon" ' '
# set -gq "@catppuccin_ctp_cpu_color" '#{l:#{cpu_bg_color}}'
# set -gq "@catppuccin_ctp_cpu_text" ' #{l:#{cpu_percentage}}'
#
# # --- 2. ctp_memory ---
# set -gq '@ram_low_bg_color' '#{E:@thm_green}'
# set -gq '@ram_medium_bg_color' '#{E:@thm_yellow}'
# set -gq '@ram_high_bg_color' '#{E:@thm_red}'
#
# set -gq "@catppuccin_ctp_memory_icon" ' '
# set -gq "@catppuccin_ctp_memory_color" '#{l:#{ram_bg_color}}'
# set -gq "@catppuccin_ctp_memory_text" ' #{l:#{ram_percentage}}'
#
# # --- 3. primary_ip ---
# set -gq "@catppuccin_primary_ip_icon" '#{l:#{primary_ip_icon}} '
# set -gqF "@catppuccin_primary_ip_color" '#{E:@thm_lavender}'
# set -gq "@catppuccin_primary_ip_text" ' #{l:#{primary_ip}}'

# ##### Status line #############################################
# set -g status-left '#{E:@catppuccin_status_session}#[fg=#{E:@thm_surface_0},bg=default] '
# set -agF status-right '#{E:@catppuccin_status_ctp_cpu}#[fg=#{E:@thm_surface_0},bg=default] '
# set -agF status-right '#{E:@catppuccin_status_ctp_memory}#[fg=#{E:@thm_surface_0},bg=default] '
#
# if 'test -n "$(find /sys/class/power_supply -maxdepth 1 -name "BAT*" 2>/dev/null)"' {
#   set -agF status-right '#{E:@catppuccin_status_battery}#[fg=#{E:@thm_surface_0},bg=default] '
# }
#
# set -ag status-right '#{E:@catppuccin_status_date_time}#[fg=#{E:@thm_surface_0},bg=default] '
